%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Save result in geometric figure
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

saveas(GeoFig,...
       [path '/GeometricFigures/Result_Geometric_t_'...
        num2str(instant) '.fig'], 'fig');

saveas(GeoFig,...
       [path '/GeometricImages/Result_Geometric_t_'...
        num2str(instant) '.jpg']);
close all;